const PRODUCTS_DATA = [
  {
    "id": "rampready-os",
    "title": "RampReady 30/60/90 Onboarding & Rubric Operating System",
    "subtitle": "Designed to Accelerate Sales Ramp & Eliminate Ramp Drift with Observable 5-Point Rubric Gates",
    "category": "flagship",
    "badge": "Flagship Digital Product #1",
    "price": 497,
    "team_price": 997,
    "enterprise_price": 2497,
    "price_display": "$497",
    "billing_type": "One-Time Purchase",
    "download_file": "RampReady-30-60-90-OS-v1.0.0.zip",
    "file_size": "13.4 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "VPs of Sales, Heads of Enablement, CROs, Sales Managers, Seed-to-Series B Founders",
    "problem": "Sales new-hire ramp frequently drifts across 6 to 9 months when teams rely on passive shadowing, unstructured link-sharing, and subjective manager evaluations that allow unprepared reps to conduct live customer calls.",
    "outcome": "Designed to accelerate new-hire ramp and establish observable field readiness. Implements a structured 4-stage progression (Know -> Practice -> Prove -> Perform) with 5-point observable rubric exit gates before live buyer access (grounded in historical practitioner experience cutting ramp from 90 to 45 days at SentinelOne and Twilio).",
    "deliverables": [
      "01-RAMPREADY-CORE-30-60-90-BLUEPRINT.md (Role milestones, exit gates & SLAs)",
      "02-STANDARDIZED-OBSERVABLE-RUBRICS.md (5 core rubrics: Outbound, Discovery, Demo, MEDDPICC, Closing)",
      "03-RUBRIC-SCORECARD-MATRIX.csv (Spreadsheet-ready manager evaluation matrix)",
      "04-AI-FLUENCY-GTM-PROMPT-PACK.md (Prompts for account forensics, roleplay & call audits)",
      "05-FRONTLINE-MANAGER-1ON1-CHECKPOINT-AGENDAS.md (Turnkey 1:1 coaching rhythms for Days 7, 30, 60, 90)",
      "06-ONBOARDING-GANTT-IMPLEMENTATION-PLAN.csv (12-week deployment timeline)",
      "README-IMPLEMENTATION-GUIDE.md (7-day fast-track deployment guide)",
      "manifest.json (Machine-readable metadata & license specifications)"
    ],
    "time_to_deploy": "Deploy in 7 days; 30/60/90 day progression cadence per sales cohort.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Eliminates months of trial-and-error by providing concrete behavioral rubrics that frontline managers can immediately use to inspect readiness, protecting executive pipeline and rep productivity.",
    "what_to_do_next": "Review the representative rubric excerpts in the preview sandbox, then configure manager calibration sessions using the 5-point evaluation scale.",
    "upsell_recommendation": {
      "title": "Offer B: GTM Diagnostic & Build Sprint ($25,000)",
      "description": "Have EZ Enablement custom-architect and embed the complete onboarding and MEDDPICC operating model into your CRM, LMS, and frontline management cadence."
    }
  },
  {
    "id": "deal-labs-suite",
    "title": "EZ Deal Labs Methodology Master Suite & Deal Lens Selector",
    "subtitle": "Active Scenario Practice, Diagnostic Rubrics & Buyer Defense Across 6 Sales Methodologies",
    "category": "methodology",
    "badge": "Complete Methodology Suite (RC3)",
    "price": 997,
    "team_price": 2497,
    "enterprise_price": 4997,
    "price_display": "$997",
    "billing_type": "One-Time Team License",
    "download_file": "EZ-Deal-Labs-Methodology-Suite-v1.0.0.zip",
    "file_size": "219.7 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Chief Revenue Officers, VPs of Sales, Enablement Leaders, Enterprise Sales Directors",
    "problem": "Sales teams invest heavily in methodology training (MEDDPICC, SPIN, Challenger) only for reps to memorize acronyms without changing live deal execution. Deals stall at Stage 2->3 when sellers fail to quantify economic pain or access Economic Buyers.",
    "outcome": "Designed to improve Stage 2 qualification consistency and reduce deal stall by replacing passive lectures with active deal simulations, 5-point observable rubrics, and realistic buyer defense. Includes the interactive Deal Lens Selector.",
    "deliverables": [
      "EZ-Deal-Lens-Selector.html (Interactive self-contained web diagnostic for reps & managers)",
      "selector_rules.json (Algorithmic decision engine & scoring logic)",
      "EZ_Enablement_Interactive_Courseware.html (Interactive standalone playable methodology lab)",
      "EZ_Enablement_Facilitator_Guide.md (Trainer & manager delivery playbook)",
      "EZ_Enablement_Learner_Field_Manual.md (Tactical quick-reference guide for reps)",
      "EZ_Enablement_Master_Manifest.md (Full curriculum catalog & answer keys)",
      "Modules 1\u20135: Scenarios, Rubrics, Exercises & Assessments across all 6 methodologies"
    ],
    "time_to_deploy": "Immediate self-serve launch; 2 hours per methodology module or 6-week phased rollout.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Provides a permanent, reusable methodology execution asset for your team, replacing recurring five-figure training subscriptions with owned internal IP.",
    "what_to_do_next": "Use the Deal Lens Selector to diagnose stalled pipeline opportunities, then assign the recommended Deal Lab exercise before executive proposals are presented.",
    "upsell_recommendation": {
      "title": "Custom AI Deal Coaching Workshop ($5,500)",
      "description": "Half-day live fire workshop with EZ breaking down your team's real active deals using the Deal Labs rubrics."
    }
  },
  {
    "id": "ez-ai-roleplay-library",
    "title": "EZ AI Sales Roleplay Library (100 Scenarios)",
    "subtitle": "100 Production-Grade Simulation Scenarios Across 6 Methodologies, 29 Skills & 12 Industries",
    "category": "ai-systems",
    "badge": "100 Scenarios \u2022 v1.0.0",
    "price": 497,
    "team_price": 1497,
    "enterprise_price": 3497,
    "price_display": "$497",
    "billing_type": "One-Time License",
    "download_file": "EZ-AI-Roleplay-Library-v1.0.0.zip",
    "file_size": "616.1 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Enablement Leads, Sales Managers, RevOps, Commercial Directors, AI Training Architects",
    "problem": "Sales reps often practice on real prospects because internal mock calls lack structure, while generic LLM prompts are too agreeable, lack behavioral friction, and fail to simulate skeptical executive buyers.",
    "outcome": "Provides a turnkey simulation engine featuring 26 realistic, skeptical executive buyer personas (analytical CFOs, security-conscious CISOs, cautious legal counsels) who challenge sellers and evaluate responses against 5-point rubrics.",
    "deliverables": [
      "100 Production-Grade JSON Scenarios (44 Methodology, 32 Core Skill, 24 Industry-Specific)",
      "26 Reusable Buyer Persona Profiles (Motivations, skepticism levels, trigger phrases, pushback patterns)",
      "4 Runtime System Prompts (buyer-system-prompt.md, evaluator-prompt.md, coach-prompt.md, loader.md)",
      "Automated Validation Suite & Test Harness (validate_roleplay_library.py + 4 test suites)",
      "Architecture & Runtime Integration Documentation (/docs/)",
      "Master CSV Catalogs (roleplay-catalog.csv, persona-catalog.csv, rubric-catalog.csv)"
    ],
    "time_to_deploy": "Immediate deployment. Load prompts and JSON scenarios into ChatGPT Team/Enterprise, Claude Projects, Gemini, or custom LLM APIs.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Saves hundreds of hours of internal scenario drafting and prompt calibration by providing tested, structured simulation schemas ready for team use.",
    "what_to_do_next": "Examine the 3 representative scenario samples in the preview sandbox, then configure the runtime prompts within your team's AI workspace.",
    "upsell_recommendation": {
      "title": "Offer A: AI Adoption Sprint ($15,000)",
      "description": "Custom API integration of the roleplay engine into your internal Slack/Teams workflows with automated coaching scorecards."
    }
  },
  {
    "id": "ai-judgment-lab",
    "title": "AI Judgment Lab for GTM Teams (Learner & Facilitator Toolkit)",
    "subtitle": "Designed to Reduce Generic AI Outreach & Compliance Risk with the 7-Step Human Judgment Loop",
    "category": "ai-systems",
    "badge": "Turnkey Courseware & Toolkit",
    "price": 397,
    "team_price": 1250,
    "enterprise_price": 3500,
    "price_display": "$397",
    "billing_type": "One-Time Toolkit License",
    "download_file": "EZ-AI-Judgment-Lab-v1.0.0.zip",
    "file_size": "6.6 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "CROs, VPs of Sales, Enablement Directors, RevOps Leaders, Enterprise GTM Teams",
    "problem": "Unchecked generative AI usage can lead to generic, hallucinated outreach and unverified claims, eroding brand trust and exposing organizations to confidential data leakage.",
    "outcome": "Instills the 7-step Human Judgment Loop (Intent -> Input -> Generate -> Inspect -> Verify -> Refine -> Decide) and 8-input AI brief to teach revenue teams how to produce accurate, source-traceable, high-quality GTM deliverables.",
    "deliverables": [
      "01-HUMAN-JUDGMENT-LOOP-FRAMEWORK.md (7-step operating model & workflow rules)",
      "02-THE-8-INPUT-AI-BRIEF-TEMPLATE.md (Standardized prompt brief for revenue teams)",
      "03-AI-OUTPUT-INSPECTION-CHECKLIST.md (6-point quality screen for reps & managers)",
      "04-NOVAPAY-SYSTEMS-PRACTICE-CASE.md (Messy real-world simulation case study)",
      "05-VERIFICATION-LADDER-AND-RUBRIC.md (Risk-tiered escalation matrix & capstone rubric)",
      "06-LMS-xAPI-STORYBOARD.json (Machine-readable curriculum & tracking events for LMS)",
      "README-FACILITATOR-GUIDE.md (Workshop run of show & 30-day reinforcement plan)"
    ],
    "time_to_deploy": "2.5-hour self-paced course or 3-hour live workshop + 30-day reinforcement cadence.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Provides a structured governance and quality control standard for AI usage, helping sellers produce tailored, credible account work while mitigating compliance risks.",
    "what_to_do_next": "Review the 8-input AI brief template excerpt, then implement the 6-point inspection checklist across outbound SDR and AE workflows.",
    "upsell_recommendation": {
      "title": "Executive AI Briefing ($3,500)",
      "description": "90-minute live interactive executive session for senior leadership on building safe, high-velocity GTM AI operating systems."
    }
  },
  {
    "id": "ai-fluency-lms-suite",
    "title": "AI Fluency for GTM Teams \u2014 Enterprise LMS Package",
    "subtitle": "Production-Ready SCORM 1.2, SCORM 2004 & xAPI Packages for Scalable Learning Management Systems",
    "category": "lms-packages",
    "badge": "SCORM 1.2 \u2022 SCORM 2004 \u2022 xAPI",
    "price": 1497,
    "team_price": 2497,
    "enterprise_price": 4997,
    "price_display": "$1,497",
    "billing_type": "Annual Unlimited Company License",
    "download_file": "EZ_Enablement_AI_Fluency_Full_Production_Suite.zip",
    "file_size": "61.7 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Corporate L&D Directors, Enterprise Enablement Leaders, Chief Commercial Officers",
    "problem": "Deploying accredited AI training across hundreds of distributed sellers often stalls when custom course authoring in authoring tools takes months of development and substantial agency budget.",
    "outcome": "Provides pre-packaged courseware ready for LMS upload (Workday, Cornerstone, Docebo, SuccessFactors, Mindtickle) with built-in score reporting, bookmarking, and xAPI telemetry.",
    "deliverables": [
      "EZ_Enablement_AI_Fluency_SCORM_1.2.zip (Standard LMS compatibility)",
      "EZ_Enablement_AI_Fluency_SCORM_2004.zip (Multi-SCO tracking & sequencing)",
      "EZ_Enablement_AI_Fluency_xAPI.zip (TinCan telemetry & LRS reporting)",
      "Course_Blueprint.md (Instructional design map & learning objectives)",
      "Assessment_Bank.md (25 scenario-based knowledge check questions with answer keys)",
      "Learner_Toolkit.md (Downloadable job aid for reps to keep in their workflow)",
      "lms_qa_report.json (Automated manifest validation and API compliance report)"
    ],
    "time_to_deploy": "Uploads directly to LMS; 60-90 minutes learner completion time.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Eliminates months of custom course authoring and outside agency fees, delivering immediate completion and readiness tracking across global cohorts.",
    "what_to_do_next": "Test package upload in your LMS staging environment and review the course blueprint.",
    "upsell_recommendation": {
      "title": "Offer A: AI Adoption Sprint ($15,000)",
      "description": "Pair digital LMS courseware with 4 weeks of hands-on workflow engineering and live team certification."
    }
  },
  {
    "id": "meddpicc-deal-lab",
    "title": "MEDDPICC Deal Execution Lab (Standalone)",
    "subtitle": "Active Qualification, Economic Buyer Access & Paper Process Verification",
    "category": "methodology",
    "badge": "Single Lab",
    "price": 297,
    "team_price": 597,
    "enterprise_price": 1250,
    "price_display": "$297",
    "billing_type": "One-Time License",
    "download_file": "EZ-Deal-Labs-Methodology-Suite-v1.0.0.zip",
    "file_size": "219.7 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Enterprise Sales Directors, AEs, Sales Managers using MEDDPICC / MEDDIC",
    "problem": "Sellers often treat MEDDPICC as an administrative checklist in CRM without practically testing Economic Buyer access or uncovering true Decision Criteria.",
    "outcome": "Interactive scenario simulation that challenges sellers to defend qualification gates, validate Champion access, and verify the paper process before committing deals.",
    "deliverables": [
      "MEDDPICC Interactive Courseware Module (HTML/JS standalone)",
      "MEDDPICC 5-Point Observable Evaluation Rubric (Metrics to Paper Process)",
      "Economic Buyer Access Scripts & Mutual Action Plan Templates",
      "Manager Deal Review Forensic Checklist"
    ],
    "time_to_deploy": "45-minute interactive simulation exercise.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Helps sales managers identify unqualified deals earlier in the sales cycle, improving forecast discipline.",
    "what_to_do_next": "Review the MEDDPICC rubric excerpt in the preview tab, then test active pipeline opportunities against the decision process criteria.",
    "upsell_recommendation": {
      "title": "Upgrade to Full Deal Labs Master Suite ($997)",
      "description": "Get all 6 methodology labs + the interactive Deal Lens Selector and LMS packages."
    }
  },
  {
    "id": "spin-deal-lab",
    "title": "SPIN Selling Deal Execution Lab (Standalone)",
    "subtitle": "Master the Art of Implication Questions & Pain Amplification",
    "category": "methodology",
    "badge": "Single Lab",
    "price": 297,
    "team_price": 597,
    "enterprise_price": 1250,
    "price_display": "$297",
    "billing_type": "One-Time License",
    "download_file": "EZ-Deal-Labs-Methodology-Suite-v1.0.0.zip",
    "file_size": "219.7 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Mid-market & Enterprise Sales Leaders, Consultative Sellers",
    "problem": "Sellers frequently rush through surface-level discovery questions and pitch product features before the customer recognizes the broader business implications of their problem.",
    "outcome": "Guides sellers through structured Implication and Need-Payoff question sequencing so buyers articulate problem severity and value in their own words.",
    "deliverables": [
      "SPIN Interactive Scenario Simulator (HTML/JS)",
      "Implication Question Bank for B2B Tech & SaaS",
      "5-Point Discovery Quality Scoring Rubric"
    ],
    "time_to_deploy": "45-minute interactive simulation.",
    "delivery_method": "Digital Delivery via Automated Webhook Fulfillment upon Live Merchant Activation (Paid Archives Excluded from Public Snapshot).",
    "why_worth_it": "Helps sellers build stronger consultative discovery habits, leading to clearer business cases and less pricing pushback.",
    "what_to_do_next": "Review the discovery question sequencing guide and test practice scenarios with your sales team.",
    "upsell_recommendation": {
      "title": "Upgrade to Full Deal Labs Master Suite ($997)",
      "description": "Unlock all 6 methodology labs and the complete selector logic engine."
    }
  },
  {
    "id": "expert-advisory-call",
    "title": "60-Minute Executive Enablement Advisory Call",
    "subtitle": "Direct 1:1 Strategic Architecture & Problem Solving with Erez 'EZ' Haimowicz",
    "category": "advisory",
    "badge": "1:1 Executive Session",
    "price": 500,
    "team_price": 500,
    "enterprise_price": 500,
    "price_display": "$500",
    "billing_type": "Per 60-Minute Session (Upfront)",
    "download_file": "EZ-Executive-Advisory-Intake-Packet.zip",
    "file_size": "15.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Heads of Enablement, VPs of Sales, Seed-to-Series B Founders, GTM Leaders",
    "problem": "Revenue leaders often need direct, unvarnished feedback on onboarding structures, sales compensation, methodology adoption, or tooling architectures without entering long advisory retainers.",
    "outcome": "Provides a focused diagnostic review, architectural recommendations, and a prioritized execution roadmap during a dedicated 60-minute strategy session.",
    "deliverables": [
      "60-minute recorded strategic video session with EZ",
      "Pre-call audit of current enablement collateral or onboarding outline",
      "Written action plan with prioritized recommendations delivered within 24 hours",
      "Direct follow-up access for 7 days"
    ],
    "time_to_deploy": "Booked upon commercial opening; sessions scheduled within 3-5 business days.",
    "delivery_method": "Intake questionnaire & calendar reservation link.",
    "why_worth_it": "Provides targeted practitioner guidance informed by real-world enablement leadership across multiple high-growth technology companies.",
    "what_to_do_next": "Submit the pre-call intake form outlining your current top operational sticking point.",
    "upsell_recommendation": {
      "title": "Hands-On Working Session ($1,250)",
      "description": "Expand to a 2-hour intensive deep-dive to build and rewrite rubrics live."
    }
  },
  {
    "id": "hands-on-working-session",
    "title": "2-Hour Hands-On Enablement Architecture Session",
    "subtitle": "Live Co-Creation & Teardown: Rubrics, Playbooks & AI Prompts Built Live",
    "category": "advisory",
    "badge": "2-Hour Intensive",
    "price": 1250,
    "team_price": 1250,
    "enterprise_price": 1250,
    "price_display": "$1,250",
    "billing_type": "Per 2-Hour Intensive (Upfront)",
    "download_file": "EZ-Working-Session-Intake-Packet.zip",
    "file_size": "18.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "VPs of Sales, Enablement Managers, RevOps Leaders building new motions",
    "problem": "Teams often know the operational assets they need to build but lack the bandwidth or structured rubrics to draft them from scratch.",
    "outcome": "Walk away from the session with completed operational assets co-developed live on screen, ready for immediate team deployment.",
    "deliverables": [
      "2 hours of intensive live screen-sharing and co-creation with EZ",
      "Completed 5-point custom rubric tailored to your specific sales motion",
      "Custom AI prompt workflows engineered for your account research cadence",
      "Recorded session and editable Google Workspace documents"
    ],
    "time_to_deploy": "Delivered within 5 business days of confirmed booking.",
    "delivery_method": "Calendar reservation + live collaborative Google Docs session.",
    "why_worth_it": "Produces finished, reviewed operational assets in 2 hours, eliminating weeks of internal drafting and committee revisions.",
    "what_to_do_next": "Submit current pitch decks or qualification rubrics for pre-session review.",
    "upsell_recommendation": {
      "title": "AI & GTM Enablement Diagnostic ($3,500)",
      "description": "Expand into a comprehensive 2-day audit across your entire GTM architecture."
    }
  },
  {
    "id": "ai-gtm-diagnostic",
    "title": "AI & GTM Enablement Diagnostic Audit (2-Day Intensive)",
    "subtitle": "Comprehensive Teardown of Your Content, Tech Stack, Rep Ramp & Coaching Cadence",
    "category": "advisory",
    "badge": "2-Day Diagnostic",
    "price": 3500,
    "team_price": 3500,
    "enterprise_price": 3500,
    "price_display": "$3,500",
    "billing_type": "Fixed Project (50% Upfront, 50% on Delivery)",
    "download_file": "EZ-GTM-Diagnostic-Scope-Intake.zip",
    "file_size": "22.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Chief Revenue Officers, VPs of Sales, Heads of Operations, Private Equity Operating Partners",
    "problem": "When pipeline conversion slows or ramp delays occur, leaders need objective diagnosis to determine whether the bottleneck is messaging, discovery rigor, manager coaching, or tooling friction.",
    "outcome": "Delivers an evidence-based forensic diagnostic report highlighting funnel drop-off points, tool utilization gaps, and a prioritized 90-day remediation blueprint.",
    "deliverables": [
      "CRM and conversation intelligence data audit (up to 20 recorded calls)",
      "Content and collateral utilization audit (Highspot / Drive / Notion analysis)",
      "Executive Readout Presentation: Root-cause findings, benchmark comparisons, and ROI roadmap",
      "30-60-90 Day Prioritized Engineering Action Plan"
    ],
    "time_to_deploy": "Completed within 10 business days from data intake.",
    "delivery_method": "Data intake -> asynchronous analysis -> 90-minute Executive Board Readout.",
    "why_worth_it": "Identifies high-impact conversion leaks and redundant software spend with clear practitioner recommendations.",
    "what_to_do_next": "Schedule a scoping discussion and provide read-only auditor access to your sales call library.",
    "upsell_recommendation": {
      "title": "Offer B: GTM Diagnostic & Build Sprint ($25,000)",
      "description": "Credit 100% of your diagnostic fee ($3,500) toward the full 6-8 week implementation sprint."
    }
  },
  {
    "id": "offer-a-ai-sprint",
    "title": "Offer A: AI Adoption & Fluency Sprint (4 Weeks)",
    "subtitle": "Designed to Reduce Administrative Friction & Certify GTM AI Prompt Fluency",
    "category": "sprints",
    "badge": "4-Week Transformation Sprint",
    "price": 15000,
    "team_price": 15000,
    "enterprise_price": 20000,
    "price_display": "$15,000",
    "billing_type": "50% Upfront / 50% on Final Milestone ($12,500 Floor)",
    "download_file": "EZ-Offer-A-Delivery-Packet.zip",
    "file_size": "25.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "CROs, VPs of Sales, Chief Commercial Officers, AI Transformation Steering Committees",
    "problem": "Organizations frequently invest in AI licenses that reps either ignore or use inconsistently for generic, unverified outreach, creating quality and brand concerns.",
    "outcome": "Deploys an audited, role-specific 8-input AI operating system across SDRs, AEs, and Managers, designed to reduce administrative preparation friction and certify team members on observable AI judgment rubrics.",
    "deliverables": [
      "Pre-Engagement Intake, Tooling Access & Baseline Telemetry Audit",
      "Weekly Live Cohort Training & Scenario Labs (4 x 90-min sessions)",
      "Custom Role-Based Prompt Operating System (Tailored to your ICP, product & CRM)",
      "Manager Inspection & Quality Gate Cadence (Weekly 15-min call forensic reviews)",
      "Executive Readout & Business Impact Scorecard presented to ELT / Board",
      "30-60-90 Day Post-Sprint Telemetry Reinforcement Guide"
    ],
    "time_to_deploy": "4-week turnkey delivery schedule with weekly structured milestones.",
    "delivery_method": "Blended consulting delivery: live virtual workshops, prompt architecture, and executive readouts.",
    "why_worth_it": "Helps your team extract practical value from existing AI tooling investments while establishing clear quality and privacy standards.",
    "what_to_do_next": "Submit an intake request to schedule a discovery consultation on team size and tooling architecture.",
    "upsell_recommendation": {
      "title": "Fractional Head of Enablement ($7,500/mo)",
      "description": "Ongoing monthly governance, prompt optimization, and quarterly manager calibration."
    }
  },
  {
    "id": "offer-b-gtm-sprint",
    "title": "Offer B: GTM Diagnostic & Build Sprint (6\u20138 Weeks)",
    "subtitle": "Complete GTM Operating Model Overhaul: Onboarding, MEDDPICC Gates & Manager OS",
    "category": "sprints",
    "badge": "Flagship Consulting Sprint",
    "price": 25000,
    "team_price": 25000,
    "enterprise_price": 35000,
    "price_display": "$25,000",
    "billing_type": "40% Kickoff / 30% Midpoint / 30% Completion ($20,000 Floor)",
    "download_file": "EZ-Offer-B-Delivery-Packet.zip",
    "file_size": "32.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "Series B+ Tech Startups, High-Growth SaaS CROs, Private Equity Operating Partners",
    "problem": "Scaling sales organizations often experience inconsistent rep ramp, forecast variability, and frontline managers who default to administrative deal-chasing rather than proactive behavioral coaching.",
    "outcome": "Builds a durable revenue operating model: standardizes onboarding around 30/60/90 rubric gates, embeds MEDDPICC qualification into CRM stages, establishes weekly manager deal clinics, and is designed to improve coaching consistency and win-rate predictability.",
    "deliverables": [
      "Full GTM Architecture & Funnel Capacity Audit",
      "Custom RampReady 30/60/90 Onboarding Blueprint with 5-point observable rubrics",
      "MEDDPICC Deal Stage-Gate Architecture configured in your CRM",
      "Frontline Sales Manager Coaching Operating System (1:1s, deal labs, forecast hygiene)",
      "Certified Live-Fire Pitch Defense program for new hires and tenured reps",
      "Comprehensive Executive Readout with Business Impact Attribution"
    ],
    "time_to_deploy": "6 to 8 weeks structured sprint execution.",
    "delivery_method": "Full-service consulting partnership with embedded practitioner architecture.",
    "why_worth_it": "Installs an enduring revenue infrastructure that supports consistent hiring, qualification rigor, and manager coaching as the team scales.",
    "what_to_do_next": "Submit an intake inquiry to review sales funnel metrics and executive onboarding priorities.",
    "upsell_recommendation": {
      "title": "Fractional Head of Enablement (Growth: $12,500/mo)",
      "description": "Retain EZ Enablement to lead quarterly revenue kickoff certifications and weekly manager deal clinics."
    }
  },
  {
    "id": "offer-c-partner-sprint",
    "title": "Offer C: Partner Enablement Launch Sprint (4\u20136 Weeks)",
    "subtitle": "Turn Passive Resellers and Channel Partners into Active Revenue Engines",
    "category": "sprints",
    "badge": "Channel & Partner Sprint",
    "price": 20000,
    "team_price": 20000,
    "enterprise_price": 28000,
    "price_display": "$20,000",
    "billing_type": "50% Upfront / 50% Completion ($17,500 Floor)",
    "download_file": "EZ-Offer-C-Delivery-Packet.zip",
    "file_size": "28.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "VPs of Channel, Alliances Leaders, CROs with partner/ecosystem co-sell models",
    "problem": "Channel partners are frequently overwhelmed by static asset libraries and disengage because their reps lack simple discovery frameworks and competitive talk-tracks.",
    "outcome": "Deploys a streamlined Partner Revenue Lifecycle, co-selling playbooks, concise partner micro-certifications, and joint territory mapping designed to strengthen indirect pipeline engagement (grounded in historical practitioner experience driving $3.1M in partner-influenced pipeline).",
    "deliverables": [
      "Partner Portal Audit & Friction Removal Plan",
      "Turnkey Partner Co-Selling Playbook & Competitive Battlecard Suite",
      "3-Tier Partner Accreditation Engine (Foundation, Discovery, Deal Defense)",
      "Joint Account Mapping & Territory Cadence Framework",
      "Partner Kickoff Webinar & Certification Run of Show",
      "Indirect Revenue Telemetry Dashboard"
    ],
    "time_to_deploy": "4 to 6 weeks structured deployment.",
    "delivery_method": "Turnkey channel consulting and collateral production.",
    "why_worth_it": "Transforms static partner portals into an active, co-selling enablement motion that partner reps can immediately execute with clients.",
    "what_to_do_next": "Submit an alliances inquiry to review tier-1 partner engagement metrics and co-selling priorities.",
    "upsell_recommendation": {
      "title": "Quarterly Partner Certification Refresher ($7,500/qtr)",
      "description": "Keep partner ecosystem certified on new product releases and competitive positioning."
    }
  },
  {
    "id": "fractional-head",
    "title": "Fractional Head of Enablement (Ongoing Retainer)",
    "subtitle": "Senior Commercial Leadership, Coaching Cadence & AI Strategy Without Executive Overhead",
    "category": "advisory",
    "badge": "Monthly Retainer",
    "price": 7500,
    "team_price": 7500,
    "enterprise_price": 12500,
    "price_display": "$7,500 / mo",
    "billing_type": "Monthly Prepay (Lite: $7,500/mo | Growth: $12,500/mo)",
    "download_file": "EZ-Fractional-Charter-Worksheet.zip",
    "file_size": "16.0 KB (Paid Archive Excluded from Public Repo)",
    "buyer": "CEOs, CROs, Series A-C Startups needing world-class enablement leadership",
    "problem": "Hiring a full-time VP of Enablement involves executive recruiting timelines and significant overhead, while sales cohorts require immediate coaching cadence and onboarding oversight.",
    "outcome": "Installs seasoned revenue enablement leadership immediately: leads weekly manager deal forensics, oversees onboarding cohorts, guides AI tool adoption, and aligns pipeline telemetry with executive leadership.",
    "deliverables": [
      "Embedded leadership (~1 day/wk Lite or ~2 days/wk Growth tier)",
      "Weekly Frontline Manager Deal Forensic Clinics",
      "Continuous Onboarding Cohort Oversight & Live-Fire Pitch Defenses",
      "Monthly Sales Kickoff Mini-Certifications",
      "Executive Leadership & Board Reporting Cadence",
      "Direct Slack and team channel access"
    ],
    "time_to_deploy": "Immediate kickoff upon agreement; 3-month initial commitment.",
    "delivery_method": "Embedded fractional leadership (virtual with optional on-site SKO/QBR attendance).",
    "why_worth_it": "Delivers experienced enablement leadership on demand, providing strategic direction and manager coaching without long-term executive hiring commitments.",
    "what_to_do_next": "Schedule an executive alignment session with EZ to discuss current sales headcount and quarterly GTM targets.",
    "upsell_recommendation": {
      "title": "Annual Executive Retainer",
      "description": "Lock in guaranteed quarterly on-site SKO and QBR facilitation with priority availability."
    }
  }
];
