(function(){
  var workSection=document.getElementById('work');
  if(!workSection)return;
  var head=workSection.querySelector('.work-head');
  var list=workSection.querySelector('.work-list');
  if(!head||!list)return;

  var intro=head.querySelector('.body-copy');
  if(intro)intro.textContent='Start with the outcome. Expand any project to see the business problem, delivery cadence, systems architecture, operating process, measurement model, and proof behind the result.';

  var impact=document.createElement('div');
  impact.className='impact-strip';
  impact.setAttribute('aria-label','Selected business and enablement outcomes');
  impact.innerHTML='<div class="impact-stat"><strong>$3.1M</strong><span>Partner-driven revenue influenced</span></div><div class="impact-stat"><strong>$1M</strong><span>Revenue built at ReUp Technologies</span></div><div class="impact-stat"><strong>+40%</strong><span>Deal conversion lift</span></div><div class="impact-stat"><strong>−37 days</strong><span>Average sales cycle reduction</span></div>';
  head.parentNode.insertBefore(impact,list);

  var projects=[
    {
      id:'sentinelone-partner-architecture',company:'SentinelOne',title:'Partner Enablement Ecosystem & Intelligence Architecture',role:'Content and Systems Manager, Partner Enablement',timeline:'2024–2025',type:'Partner ecosystem transformation',metrics:['$3.1M revenue influenced','40–50% faster ramp','4,000+ partners reached'],
      objective:'Replace a fragmented partner enablement environment with a unified operating system for role-based learning, accreditation, knowledge access, telemetry, and AI-assisted support.',
      lede:'Rebuilt the partner enablement operating environment as a connected system instead of a collection of courses, portals, and repositories.',
      why:'GTM collateral was decentralized across repositories, leadership lacked reliable visibility into partner learning and accreditation velocity, and legacy learning paths did not differentiate the needs of resellers, distributors, MSP/MSSPs, system integrators, technical roles, and sellers.',
      how:'Designed modular partner tracks, connected the PRM, LMS, content, and knowledge layers, built custom widgets and portal automations to close integration gaps, centralized searchable content, and established telemetry for enrollment, completion, accreditation, readiness, and partner impact. The architecture also created the foundation for conversational AI support using governed enablement content.',
      process:['Baseline content + learner data','Segment partner types + roles','Define capability model','Design modular learning paths','Map accreditation rules','Connect PRM + LMS workflows','Centralize knowledge + content','Instrument telemetry + dashboards','Pilot with priority audiences','Launch + reinforce globally','Optimize from readiness + revenue data'],
      pm:['Ran curriculum, portal experience, systems integration, content governance, analytics, and AI knowledge support as connected workstreams.','Used a dependency map across identity, enrollment, access, completion logic, accreditation, reporting, and launch communications so system changes did not break the learner journey.','Released priority learning experiences in waves while deeper integrations continued, reducing time-to-value without waiting for a single big-bang launch.','Reviewed adoption, completion, accreditation velocity, content usage, and field feedback on a recurring cadence to prioritize optimization.'],
      programs:['Partner Pre-Sales Fundamentals','Sales Fundamentals','Sales Applied — three-course track','Pre-Sales Technical Fundamentals','PurpleAI Partner Specialization','Cloud Fundamentals + persona learning','Unified Demo Introduction','Competitive Edge weekly series','PartnerPulse Learning Series — 4,000+ partners reached'],
      tools:['Thought Industries / SentinelOne University','Highspot / SalesEdge','Impartner PRM','Wistia','Articulate 360 / Rise','Glean','11Labs','Canva','Google Workspace','Slack Canvas','Custom widgets + portal automations','Conversational AI / RAG architecture'],
      outcomes:[['$3.1M','Partner-driven revenue influenced'],['40–50%','Reduction in partner ramp time'],['4,000+','Partners reached through structured programming'],['First','Usable analytics baseline for accreditation velocity']],
      note:'Partner Type → Role → Capability → Learning → Practice → Accreditation → Telemetry → Readiness → Partner Revenue.',
      timeToImpact:'24-week build to scaled launch · leading indicators visible by weeks 8–12 · 90-day post-launch impact review',
      phases:[['01','Audit + baseline','Weeks 1–3','Inventory learning, content, access paths, completion data, and reporting gaps.'],['02','Segmentation + capability model','Weeks 4–5','Define partner types, roles, required competencies, and target readiness outcomes.'],['03','Learning + accreditation design','Weeks 6–9','Build modular paths, prerequisites, practice, assessment, and accreditation logic.'],['04','Content + system build','Weeks 10–14','Develop priority curricula while configuring LMS, PRM, content, and knowledge workflows.'],['05','Integration + telemetry','Weeks 15–17','Connect identity, enrollment, completions, content access, and reporting events.'],['06','Pilot + QA','Weeks 18–20','Pilot priority tracks, validate learner experience, fix data and access issues, and calibrate assessments.'],['07','Scaled launch','Weeks 21–24','Roll out globally with manager/partner communications, support paths, and dashboards.'],['08','Optimize + intelligence','Month 7 onward','Use ramp, accreditation, content, support, and partner-revenue signals to improve the system and expand AI support.']],
      architecture:[['Partner identity','Reseller · Distributor · MSP/MSSP · System Integrator · Technical · Sales'],['Portal + access','Impartner PRM · partner identity · role/access logic'],['Learning','Thought Industries · Articulate Rise · Wistia · assessments'],['Content + knowledge','Highspot · Glean · Google Workspace · Canva'],['Intelligence','Telemetry · dashboards · custom widgets · conversational AI / RAG'],['Business output','Accreditation · readiness · faster ramp · partner revenue']],
      analytics:[['Adoption funnel','Invited → enrolled → started → completed → accredited'],['Learning velocity','Median days to first course, path completion, and accreditation'],['Quality','Assessment pass rate, retry rate, content drop-off, support/search friction'],['Readiness','Role/capability coverage and accredited-partner penetration by segment'],['Usage','Portal sessions, content engagement, search success, repeat usage'],['Business impact','Partner-sourced/influenced pipeline, revenue, ramp time, and program cohort comparisons']],
      evidence:[['Video learning','Working with Channel Partners','Representative partner learning asset connected to the wider readiness architecture.','Working%20with%20Channel%20Partners.mp4'],['Framework','4-Stage Enablement Framework','Know → Practice → Prove → Perform applied as the readiness model.','#artifact-framework'],['Measurement design','Partner Readiness Scorecard','Adoption, accreditation velocity, readiness coverage, and partner-revenue signals managed as one measurement model.',null]]
    },
    {
      id:'sentinelone-partnerstruck',company:'SentinelOne',title:'Partnerstruck — Gamified SKO Engagement & Certification',role:'Content and Systems Manager, Partner Enablement',timeline:'Global Sales Kickoff',type:'Gamified learning + automated remediation',metrics:['99% entry rate','68% first-pass','+30 remediated'],
      objective:'Use a live global SKO experience to build partner-ecosystem literacy, measure comprehension in real time, and automatically remediate knowledge gaps after the event.',
      lede:'Turned a global SKO into an interactive partner-learning environment with measurable comprehension instead of passive attendance.',
      why:'Traditional presentations could generate attendance without proving understanding. Leadership needed a scalable way to establish a partner-ecosystem baseline across a large audience, surface specific knowledge gaps, and close them without manual follow-up.',
      how:'Built a mobile partner-ecosystem assessment accessed through physical and digital QR touchpoints, automated scoring and pass/fail logic, targeted remediation for missed concepts, and a follow-up reassessment loop. Gamification and a custom branded fuzzy-goat reward increased participation while the backend produced real-time coverage data.',
      process:['Define ecosystem literacy outcomes','Write + validate assessment','Build QR entry points','Configure scoring thresholds','Test mobile learner journey','Launch at SKO','Monitor participation live','Route misses to micro-learning','Reassess after remediation','Report certification coverage'],
      pm:['Coordinated learning design, event logistics, QR placement, scoring rules, remediation content, rewards, and completion tracking as one experience.','Ran pre-event QA across device types and failure scenarios so the live experience could support hundreds of participants without manual intervention.','Used real-time participation and pass-rate data during SKO to identify gaps while the audience was still engaged.','Extended the learning loop after the event so first-pass misses became targeted reinforcement instead of permanent failure.'],
      programs:['Partnerstruck ecosystem assessment','QR-based venue learning journey','Automated scoring + pass/fail logic','Targeted micro-learning remediation','Post-event reassessment','Certification follow-up','Gamified fuzzy-goat reward'],
      tools:['QR workflow','Mobile assessment','Automated scoring logic','Backend tracking automation','Micro-learning remediation','Event analytics','Certification workflow'],
      outcomes:[['99%','Entry rate among SKO attendees'],['68%','First-pass certification rate'],['+30','Additional participants converted through remediation']],
      note:'Engage → Assess → Score → Diagnose → Remediate → Reassess → Certify → Report.',
      timeToImpact:'6-week build · live impact during SKO · remediation and final coverage measured within 2 weeks after event',
      phases:[['01','Define + design','Weeks 1–2','Set partner-literacy objectives, blueprint the experience, and establish pass/fail standards.'],['02','Build + automate','Weeks 3–4','Create assessment, QR flow, scoring logic, tracking, rewards, and remediation content.'],['03','QA + rehearsal','Week 5','Test devices, links, scoring, capacity, reporting, and contingency paths.'],['04','Launch','Week 6 / SKO','Run the live experience and monitor participation, completion, and pass rate in real time.'],['05','Remediate','Days 1–7 post-SKO','Send targeted micro-learning based on missed concepts and trigger reassessment.'],['06','Close the loop','Days 8–14 post-SKO','Finalize certification coverage, identify persistent gaps, and report results to leadership.']],
      architecture:[['Venue layer','Physical + digital QR entry points'],['Assessment','Mobile partner-ecosystem assessment'],['Automation','Instant scoring + pass/fail logic'],['Learning','Targeted remediation modules by missed concept'],['Engagement','Gamified reward + visible participation'],['Output','Participation · comprehension · certification · coverage']],
      analytics:[['Participation','Unique entries, starts, completions, completion rate'],['Comprehension','First-pass score, question-level miss rate, topic-level gaps'],['Remediation','Assigned → consumed → reassessed → passed'],['Experience health','QR failures, device issues, abandonment points, support requests'],['Coverage','Certified participants and residual knowledge gaps by cohort'],['Efficiency','Manual admin avoided through automated scoring and routing']],
      evidence:[['Experience design','QR Learning Journey','Physical SKO moments connected to measurable mobile learning and live analytics.',null],['Automation','Closed-Loop Remediation','Missed concepts triggered targeted follow-up rather than generic retraining.',null],['Measurement','Question-Level Gap Analysis','Assessment telemetry identified exactly which partner concepts required reinforcement.',null]]
    },
    {
      id:'twilio-soar',company:'Twilio',title:'SOAR — Sales Outcomes Achieve Results Enablement Framework',role:'Senior Sales Enablement Manager, Growth & Training',timeline:'2022–2024',type:'Global sales + partner accreditation',metrics:['+9% productivity','+40% conversion','82% MEDDPICC adoption'],
      objective:'Build a scalable competency and accreditation program that moved sellers and partners from knowledge to applied execution across discovery, value, competition, revenue process, and manager coaching.',
      lede:'Built a global competency system around the selling behaviors that mattered most to revenue execution.',
      why:'Sellers and partners lacked a shared performance standard for value-based conversations, discovery, competitive execution, and deal process. Hyper-growth required a program that could scale beyond live training and prove whether behaviors were changing in the field.',
      how:'Created a five-module SOAR curriculum, launched the first 400-person cohort, automated certification and badging, reinforced MEDDPICC inside the workflow, and connected field intelligence from Gong, Salesforce, managers, and enablement systems back into coaching and program iteration.',
      process:['Diagnose skill + pipeline gaps','Define competency model','Build five-module curriculum','Create practice + certification','Pilot with target cohort','Launch to 400 participants','Reinforce through managers + workflow','Track MEDDPICC + behavior adoption','Compare conversion + productivity','Iterate from field data'],
      pm:['Aligned Sales, Revenue Operations, managers, partners, and system owners around a common competency model and success measures.','Sequenced formal learning, applied practice, certification, manager reinforcement, and workflow support so SOAR operated as a performance system rather than a course.','Used behavioral adoption and pipeline conversion signals to decide where reinforcement was required.','Scaled through reusable curriculum, automation, certification infrastructure, and manager-led reinforcement.'],
      programs:['Value-based selling','Advanced competitive intelligence','Customer discovery','Revenue execution','Management coaching','MEDDPICC reinforcement','Automated accreditation + badging'],
      tools:['Salesforce','Gong','Highspot','Rattle','Slack','6sense','WiseOwl AI assistant','LLM systems','Workflow automation','Certification pipeline'],
      outcomes:[['+9%','Global sales productivity'],['+40%','Deal conversion lift'],['82%','MEDDPICC adoption'],['$700K','Annual savings from GTM-tool consolidation']],
      note:'Diagnose → Learn → Practice → Prove → Apply → Reinforce → Inspect → Improve.',
      timeToImpact:'12-week v1 launch · behavior adoption measured within 30–60 days · pipeline impact reviewed at 90 days and by quarter',
      phases:[['01','Diagnose','Weeks 1–2','Use pipeline, manager, rep, and conversation data to prioritize the highest-value capability gaps.'],['02','Architect','Weeks 3–4','Define competencies, learning objectives, practice standards, certification, and manager role.'],['03','Build','Weeks 5–7','Create five modules, applied exercises, assessments, job aids, automation, and badges.'],['04','Pilot','Weeks 8–9','Run a target cohort, calibrate scoring, collect friction data, and fix the learner/manager experience.'],['05','Launch','Weeks 10–12','Scale to the initial 400-person audience with communications, dashboards, and manager reinforcement.'],['06','Adoption sprint','Days 30–60','Inspect MEDDPICC usage, practice quality, manager coaching, and workflow adoption.'],['07','Business impact','Day 90 + quarterly','Compare productivity, conversion, and pipeline-quality signals; iterate by capability gap.']],
      architecture:[['Competencies','Value · competition · discovery · execution · coaching'],['Learning','Five-module SOAR curriculum'],['Practice','Applied selling scenarios + manager reinforcement'],['Accreditation','Automated badges + certificates'],['Workflow','Salesforce · Rattle · WiseOwl · LLM support'],['Business output','Productivity · conversion · methodology adoption']],
      analytics:[['Learning funnel','Assigned → started → completed → certified'],['Skill evidence','Practice score, certification score, first-pass rate, retry patterns'],['Behavior adoption','MEDDPICC field completion, manager inspection, Gong-observed behaviors'],['Pipeline quality','Stage conversion, qualification completeness, slippage, next-step quality'],['Productivity','Seller activity-to-outcome efficiency and time spent finding answers'],['Business impact','Conversion lift, productivity lift, and cohort/period comparisons']],
      evidence:[['Performance model','4-Stage Enablement Framework','Know → Practice → Prove → Perform used to connect learning to field execution.','#artifact-framework'],['Architecture','8-Week Enablement Accelerator','Representative build sequence for diagnosis, design, pilot, launch, and measurement.','#artifact-accelerator'],['Measurement','SOAR Performance Scorecard','Learning, methodology adoption, manager reinforcement, and pipeline outcomes tracked together.',null]]
    },
    {
      id:'twilio-gong-intelligence',company:'Twilio',title:'Gong Conversational Intelligence Architecture & Data Pipeline',role:'Senior Sales Enablement Manager, Growth & Training',timeline:'2022–2024',type:'Conversation intelligence + performance analytics',metrics:['400+ participants supported','VoC telemetry','Closed-loop coaching'],
      objective:'Turn Gong from a call repository into an evidence engine that continuously identified field behaviors, buyer friction, competitive patterns, and coaching priorities.',
      lede:'Converted customer conversations into a repeatable data-to-action loop for enablement and manager coaching.',
      why:'Revenue leaders lacked empirical evidence showing what strong reps did differently, where deals stalled, which objections repeated, and whether enablement changed real behavior. Program priorities risked being driven by anecdote instead of field evidence.',
      how:'Built keyword dictionaries, custom trackers, cohort filters, and analytics views; partnered with Sales Operations to extract conversation telemetry; compared top-rep and stalled-deal patterns; and fed recurring gaps into SOAR, manager coaching, job aids, and follow-up measurement.',
      process:['Define business questions','Select observable behaviors','Build tracker dictionary','Segment cohorts + calls','Validate tracker precision','Establish analytics baseline','Compare top-performer + stalled-deal patterns','Translate gaps into enablement','Coach + reinforce','Measure post-enablement behavior'],
      pm:['Partnered with Sales Operations and revenue leadership to define observable signals tied to business questions.','Maintained tracker governance so dictionaries stayed useful as products, objections, competitors, and messaging changed.','Established a recurring insight cadence connecting conversation data to curriculum, coaching, and manager reinforcement.','Measured the same behaviors after intervention to determine whether the enablement changed field execution.'],
      programs:['Voice-of-customer analysis','Custom conversation trackers','Behavior analytics','Objection intelligence','Competitive friction analysis','SOAR curriculum inputs','Manager coaching insights'],
      tools:['Gong','Salesforce','Sales Operations data pipeline','Highspot','Custom trackers','Keyword dictionaries','Advanced filters','Manager coaching workflows'],
      outcomes:[['400+','SOAR participants supported by the intelligence loop'],['+9%','Productivity lift in the resulting program'],['+40%','Conversion gain in the resulting program']],
      note:'Conversation → Signal → Pattern → Skill Gap → Enablement → Coaching → Behavior Change → Revenue.',
      timeToImpact:'8-week instrumentation + baseline · useful patterns by weeks 6–8 · behavior-change reads 30–60 days after intervention',
      phases:[['01','Questions + taxonomy','Week 1','Define the revenue questions, behaviors, objections, competitors, and topics worth detecting.'],['02','Instrumentation','Weeks 2–3','Build trackers, keywords, filters, cohorts, and dashboards.'],['03','Validation','Week 4','Review sample calls, tune false positives/negatives, and confirm data quality.'],['04','Baseline','Weeks 5–6','Establish behavioral norms by segment, performer level, stage, and outcome.'],['05','Insight sprint','Weeks 7–8','Identify recurring patterns and convert them into prioritized enablement actions.'],['06','Intervention','Weeks 9–12','Deploy SOAR, coaching, manager prompts, and job aids against observed gaps.'],['07','Behavior read','30–60 days later','Re-run the same measures and compare behavior by cohort and pipeline outcome.']],
      architecture:[['Conversation layer','Gong calls + transcripts'],['Detection','Keyword dictionaries · custom trackers'],['Analytics','Filters · talk ratios · objections · topic patterns'],['Data partnership','Sales Operations telemetry + Salesforce context'],['Action layer','SOAR · coaching · manager reinforcement · Highspot'],['Business output','Evidence-based skill priorities + behavior change']],
      analytics:[['Coverage','Calls captured and analyzable by team, stage, segment, and rep'],['Tracker quality','Precision, false positives, false negatives, and tracker drift'],['Behavior','Talk/listen balance, discovery depth, objection patterns, next-step language'],['Outcome linkage','Behavior frequency by won/lost/stalled deal and top-performer cohort'],['Intervention','Pre/post behavior change after training or coaching'],['Business impact','Stage conversion, productivity, and conversion metrics tied back to the resulting program']],
      evidence:[['Intelligence map','Conversation-to-Enablement Loop','Customer conversations became a structured input into program design, coaching, and post-intervention measurement.',null],['Program linkage','SOAR Catalyst','Conversation intelligence identified the competency gaps addressed by SOAR.',null],['Governance','Tracker Quality Review','A recurring validation process kept conversation signals accurate enough to drive enablement decisions.',null]]
    },
    {
      id:'reup-gtm',company:'ReUp Technologies',title:'0 → $1M GTM & Partner Commercialization Engine',role:'Co-Founder',timeline:'2020–2022',type:'Founder-led business + GTM build',metrics:['$1M revenue','0→1 GTM build','Founder-led commercialization'],
      objective:'Build the commercial operating system required to take an early-stage company from idea to repeatable revenue across positioning, sales, partnerships, onboarding, and feedback loops.',
      lede:'Co-founded ReUp Technologies and built the commercial foundation that helped take the business from 0 to $1M in revenue.',
      why:'There was no mature company infrastructure to inherit. The business needed to define the market problem, clarify target customers and partners, create credible positioning, build repeatable discovery and qualification, and turn founder knowledge into a commercial system.',
      how:'Built positioning, value proposition, full-funnel messaging, discovery, qualification, sales playbooks, partner activation, onboarding, and operating workflows. Customer, partner, and pipeline feedback continuously fed back into the GTM model so the motion improved as the company learned.',
      process:['Define market problem','Identify ICP + partner profile','Validate positioning','Build value proposition + messaging','Install discovery + qualification','Create sales playbooks','Launch partner motion','Build onboarding','Instrument pipeline feedback','Iterate + scale repeatable execution'],
      pm:['Balanced company-building and commercialization with limited early-stage resources and no inherited operating system.','Converted founder knowledge into reusable messaging, qualification, playbooks, partner workflows, and onboarding assets.','Used active deal, customer, partner, and market feedback to continually refine the commercial model.','Prioritized the smallest repeatable system that could produce revenue, then added process as evidence and scale required it.'],
      programs:['GTM positioning + value proposition','Full-funnel messaging','Discovery + qualification architecture','Sales playbooks','Partner activation','Partner onboarding','Commercial operating processes','Pipeline feedback + iteration loops'],
      tools:['GTM operating model','Sales playbooks','Qualification frameworks','Partner onboarding workflows','Messaging architecture','Pipeline review','Founder-led commercialization'],
      outcomes:[['$1M','Revenue built at ReUp Technologies'],['0→1','Commercial operating foundation'],['Co-Founder','Direct ownership of business-building + GTM execution']],
      note:'Market Signal → Positioning → Sales Motion → Partner Motion → Customer Feedback → Repeatable Revenue.',
      timeToImpact:'90-day commercial foundation · 6–12 months to repeatable motion · continued scale through 2022',
      phases:[['01','Problem + ICP','Weeks 1–3','Clarify the market problem, target customer, partner profile, and buying context.'],['02','Positioning','Weeks 4–6','Build value proposition, category narrative, proof points, and core messaging.'],['03','Sales motion','Weeks 7–10','Create discovery, qualification, objection handling, and opportunity process.'],['04','Partner motion','Weeks 11–13','Define partner value, activation, onboarding, and co-selling expectations.'],['05','First operating system','Months 4–6','Standardize playbooks, onboarding, pipeline cadence, and commercial workflows.'],['06','Repeatability','Months 7–12','Use win/loss, pipeline, customer, and partner data to refine the motion.'],['07','Scale','Year 2','Expand what repeatedly produced revenue while removing founder-only dependencies.']],
      architecture:[['Market signal','Customer + partner problems'],['Positioning','Value proposition + commercial narrative'],['Revenue motion','Discovery · qualification · sales playbooks'],['Partner motion','Activation · onboarding · co-selling'],['Operating layer','Pipeline cadence · repeatable workflows · knowledge transfer'],['Business output','$1M revenue + repeatable GTM foundation']],
      analytics:[['Demand','Qualified opportunities created and source mix'],['Pipeline','Stage conversion, velocity, aging, slippage, and coverage'],['Sales quality','Discovery/qualification completeness and objection patterns'],['Partners','Partner activation, sourced/influenced opportunities, and time-to-first-value'],['Customers','Win/loss reasons, onboarding friction, retention signals, and feedback themes'],['Business impact','Revenue growth, repeatability, and decreasing founder dependency']],
      evidence:[['Commercial result','$1M Revenue','The commercial system helped build ReUp into a revenue-generating business rather than a concept-only startup.',null],['Operating model','Founder Knowledge → Repeatable GTM','Messaging, qualification, partner activation, and onboarding were converted into reusable systems.',null],['Measurement','Commercial Health Scorecard','Pipeline velocity, partner contribution, win/loss, and customer feedback guided iteration.',null]]
    },
    {
      id:'enterprise-revenue-acceleration',company:'Cofense & Prior Enterprise Roles',title:'Revenue Acceleration & Sales Cycle Optimization',role:'Senior Revenue & Go-To-Market Enablement Leader',timeline:'Enterprise GTM leadership',type:'Revenue performance + onboarding',metrics:['+8.75% revenue','+4% win rate','−37 days cycle'],
      objective:'Improve enterprise revenue performance by connecting onboarding, qualification, coaching, manager reinforcement, and workflow design to measurable pipeline outcomes.',
      lede:'Connected enablement directly to enterprise revenue performance instead of measuring training volume.',
      why:'Complex enterprise deals stalled because discovery and qualification quality varied by rep and manager, while fragmented onboarding extended time-to-productivity and made reinforcement inconsistent.',
      how:'Standardized discovery and qualification, rebuilt onboarding around role readiness, deployed targeted coaching and manager sessions, established continuous education, and used CRM and enablement workflows to reduce administrative friction. Program decisions were tied to win rate, sales-cycle movement, and revenue outcomes.',
      process:['Baseline funnel + ramp performance','Identify friction by stage','Standardize discovery + qualification','Rebuild role-based onboarding','Create coaching interventions','Enable frontline managers','Automate repeatable workflow','Inspect stage conversion + cycle','Run quarterly improvement sprints'],
      pm:['Prioritized business problems using funnel, ramp, and field evidence rather than training requests alone.','Balanced onboarding, continuous education, manager coaching, and workflow improvement as one performance system.','Used standardized discovery and qualification criteria to reduce rep-to-rep execution variance.','Reviewed leading indicators monthly and lagging revenue outcomes quarterly to decide where to reinforce or redesign.'],
      programs:['Structured enterprise onboarding','Discovery + qualification frameworks','Manager enablement','Targeted coaching modules','Continuous education','Competitive deal reinforcement','Revenue workflow optimization'],
      tools:['Allego','LMS learning paths','Sales playbooks','CRM workflows','Video practice','Certification workflows','Manager coaching','Enablement analytics'],
      outcomes:[['+8.75%','Overall bottom-line revenue'],['+4%','Competitive win rate'],['−37 days','Average sales cycle']],
      note:'Diagnose → Standardize → Practice → Coach → Inspect → Reinforce → Improve.',
      timeToImpact:'16-week v1 operating system · leading indicators within 30–60 days · full pipeline impact read across 1–2 quarters',
      phases:[['01','Baseline','Weeks 1–2','Measure ramp, stage conversion, cycle time, win rate, and manager/rep friction.'],['02','Diagnose','Weeks 3–4','Identify the highest-value capability and process gaps by stage and role.'],['03','Standardize','Weeks 5–7','Create discovery, qualification, onboarding, and coaching standards.'],['04','Build + pilot','Weeks 8–11','Launch role-based learning, practice, manager reinforcement, and workflow changes with target teams.'],['05','Scale','Weeks 12–16','Expand the proven motion and instrument dashboards and inspection cadence.'],['06','Behavior read','Days 30–60','Measure adoption, manager inspection, qualification quality, and stage movement.'],['07','Revenue read','Quarter 1–2','Evaluate cycle time, competitive win rate, and revenue movement; prioritize the next sprint.']],
      architecture:[['Revenue motion','Complex enterprise pipeline'],['Method','Discovery · qualification · competitive execution'],['Learning','Onboarding · coaching · continuous education'],['Manager layer','Reinforcement + inspection'],['Workflow','CRM + enablement automation'],['Business output','Revenue lift · win-rate lift · shorter cycles']],
      analytics:[['Ramp','Time to certification, first qualified opportunity, first pipeline, first win'],['Adoption','Framework usage, certification, manager coaching, playbook usage'],['Pipeline quality','Stage conversion, qualification completeness, slippage, and aging'],['Velocity','Days in stage, end-to-end cycle time, stalled-deal rate'],['Win rate','Overall and competitive win rate by cohort/segment'],['Business impact','Revenue, productivity, and performance comparison before/after intervention']],
      evidence:[['Operating model','Revenue Acceleration Loop','Field skill, manager reinforcement, workflow, and measurement operated as a closed loop.',null],['Scorecard','Enterprise Performance Outcomes','Revenue, win-rate, cycle-time, and ramp measures formed the proof layer.','#artifact-kpis'],['Cadence','Monthly Leading / Quarterly Lagging Review','Leading execution signals were inspected before waiting for revenue outcomes.',null]]
    },
    {
      id:'global-experiential-engine',company:'Career-Wide Execution',title:'Global Enablement Cadences & Experiential Learning Engine',role:'Senior Revenue & Partner Enablement Leader',timeline:'Across organizations',type:'Global enablement operating system',metrics:['100% quarterly coverage','82% MEDDPICC','Experiential learning'],
      objective:'Build a repeatable global enablement operating cadence that maintained role coverage, technical depth, practice, certification, and manager reinforcement across changing GTM priorities.',
      lede:'Built learning systems that made enablement continuous, role-specific, measurable, and memorable instead of a sequence of disconnected events.',
      why:'Fast-moving technology organizations routinely outpaced ad-hoc training. Product changes, methodology updates, competitive shifts, and specialized technical roles required a cadence that could continuously prioritize, teach, practice, prove, and reinforce the right capabilities.',
      how:'Institutionalized quarterly enablement calendars, role-specific tracks for sellers and technical teams, manager reinforcement, and experiential learning including Jeopardy-style SKO games, fishbowl sessions, MEDDPICC pop-dart workshops, leaderboards, and live dashboards.',
      process:['Collect quarterly business priorities','Score capability gaps','Build role-based quarterly plan','Develop + QA learning','Launch knowledge layer','Run applied practice','Prove with assessment/certification','Reinforce through managers','Measure adoption + field signals','Carry gaps into next-quarter plan'],
      pm:['Managed enablement as a recurring business cadence with quarterly planning and monthly inspection instead of event-by-event fulfillment.','Balanced global consistency with role-specific depth for commercial sellers, Solution Engineers, Security Engineers, and partners.','Designed practice mechanics, scoring, dashboards, and reinforcement into the experience so engagement produced usable evidence.','Used completion, certification, methodology adoption, manager activity, and field outcomes to decide what persisted into the next cycle.'],
      programs:['Global quarterly enablement calendars','Solution Engineer technical curriculum','Security Engineer technical curriculum','Jeopardy-style SKO game shows','Interactive fishbowl sessions','MEDDPICC pop-dart workshops','Competitive leaderboards','Live learning dashboards'],
      tools:['Enablement calendars','Live dashboards','Gamified assessments','Leaderboards','Role-based technical curricula','Manager reinforcement','Certification + adoption tracking'],
      outcomes:[['100%','Quarterly learning coverage across global GTM teams'],['82%','MEDDPICC adoption'],['Repeatable','Operating cadence connecting priorities to field execution']],
      note:'Prioritize → Learn → Practice → Prove → Reinforce → Measure → Reprioritize.',
      timeToImpact:'8-week quarterly build cycle · monthly leading-indicator reviews · quarterly business-impact review',
      phases:[['01','Prioritize','Weeks 1–2','Collect business changes, pipeline friction, field feedback, and capability gaps; score by impact and urgency.'],['02','Design','Weeks 3–4','Define role outcomes, learning/practice format, managers’ role, and proof standard.'],['03','Build + QA','Weeks 5–6','Create assets, assessments, facilitation, dashboards, and communications; validate globally.'],['04','Launch knowledge','Week 7','Deliver concise role-relevant knowledge and job aids.'],['05','Practice + prove','Week 8','Run live practice, games, fishbowls, roleplays, scoring, and certification.'],['06','Reinforce','Weeks 9–12','Managers coach against the same behaviors and teams use workflow/job aids in live work.'],['07','Inspect','Monthly','Review adoption, proficiency, manager reinforcement, and field signals.'],['08','Business review','Quarterly','Compare pipeline/revenue outcomes and feed persistent gaps into the next planning cycle.']],
      architecture:[['Business priorities','Product · GTM · methodology · competitive changes'],['Calendar','Quarterly planning + monthly inspection cadence'],['Role paths','Seller · SE · Security Engineer · partner'],['Experience','Knowledge · games · fishbowls · roleplays · applied practice'],['Measurement','Completion · proficiency · manager reinforcement · field adoption'],['Output','Continuous coverage + measurable execution']],
      analytics:[['Coverage','Priority roles and capabilities covered vs. planned'],['Adoption','Assigned, started, completed, certified, and asset usage'],['Proficiency','Assessment, roleplay, certification, and scenario scores'],['Reinforcement','Manager coaching frequency and evidence of inspection'],['Behavior','Methodology and workflow adoption in CRM/conversations'],['Business impact','Conversion, cycle time, productivity, win rate, and ramp where attributable']],
      evidence:[['Cadence','Global Enablement Calendar','A recurring operating rhythm designed to prevent capability coverage gaps.',null],['Methodology','MEDDPICC Practice System','Experiential practice and manager reinforcement supported 82% methodology adoption.',null],['Measurement','Quarterly Enablement Business Review','Coverage, proficiency, adoption, and revenue signals were reviewed as one operating scorecard.',null]]
    },
    {
      id:'cybersecurity-threat-enablement',company:'Tessian · Cofense · Mimecast · Proofpoint Ecosystems',title:'Cybersecurity GTM Enablement & Threat Intelligence Architecture',role:'Senior Enablement Leader',timeline:'Cybersecurity career execution',type:'Technical cybersecurity enablement',metrics:['+8.75% revenue','+4% win rate','−37 days cycle'],
      objective:'Translate complex email security, human-layer defense, anti-phishing, and threat-intelligence concepts into repeatable commercial, technical, and partner motions.',
      lede:'Made highly technical cybersecurity concepts usable by sellers, technical teams, and partners without flattening the complexity buyers cared about.',
      why:'Enterprise buyers faced BEC, credential harvesting, phishing, insider risk, and incident-response complexity. Sellers needed to translate technical differentiation into business impact for CISOs while technical teams and partners needed aligned discovery, demo, and proof-of-concept standards.',
      how:'Built threat-centric curriculum, security buyer personas, commercial messaging, role-specific technical tracks, MEDDPICC-aligned qualification, competitive reinforcement, and PoC readiness. Threat intelligence and field evidence continuously updated the learning and sales motion.',
      process:['Track evolving threats + product changes','Translate technical detail into buyer risk','Define security personas + use cases','Build seller messaging + discovery','Build SE/Security Engineer tracks','Align qualification + PoC criteria','Practice objections + competition','Certify readiness','Measure win rate + velocity','Refresh from threat + field intelligence'],
      pm:['Maintained alignment between product/technical depth and commercial usability across sellers, technical roles, and partners.','Updated learning as threat patterns, product capabilities, objections, and competitor narratives changed.','Used persona-specific discovery and value stories to anchor technical conversations to operational and business risk.','Separated knowledge, practice, technical proof, and manager reinforcement so readiness was demonstrated rather than assumed.'],
      programs:['Threat-centric curriculum','Human-layer defense enablement','Anti-phishing architecture training','Solution Engineer technical tracks','Security Engineer technical tracks','Partner technical enablement','CISO discovery + qualification','PoC readiness'],
      tools:['MEDDPICC-aligned qualification','Technical roleplay','PoC workflows','Competitive battlecards','Threat-intelligence content','Manager coaching','Enablement analytics'],
      outcomes:[['+8.75%','Overall bottom-line revenue'],['+4%','Competitive win-rate improvement'],['−37 days','Average enterprise sales cycle']],
      note:'Threat Signal → Buyer Risk → Discovery → Technical Story → Qualification → PoC → Business Value → Close.',
      timeToImpact:'10-week core build · 30–60 day behavior read · pipeline and win-rate impact reviewed over the following quarter',
      phases:[['01','Threat + buyer map','Weeks 1–2','Map threat vectors, product capabilities, personas, buying triggers, and common enterprise objections.'],['02','Commercial translation','Weeks 3–4','Convert technical detail into discovery, business impact, value stories, and qualification criteria.'],['03','Technical tracks','Weeks 5–6','Build SE, Security Engineer, and partner paths for demo, architecture, and PoC readiness.'],['04','Practice + proof','Weeks 7–8','Run roleplays, technical scenarios, objection handling, competitive practice, and certification.'],['05','Launch + manager layer','Weeks 9–10','Scale materials and manager reinforcement into active opportunities.'],['06','Behavior read','Days 30–60','Inspect discovery quality, technical proof, messaging adoption, and competitive execution.'],['07','Pipeline impact','Quarterly','Review win rate, cycle time, stage conversion, and recurring field friction; refresh content.']],
      architecture:[['Threat intelligence','BEC · phishing · credential theft · insider risk'],['Buyer context','CISO · InfoSec · Compliance · technical stakeholders'],['Commercial story','Risk · operational impact · ROI · value'],['Technical readiness','SE · Security Engineer · partner tracks'],['Qualification + proof','MEDDPICC-aligned discovery · demo · PoC'],['Business output','Higher win rate + faster enterprise close']],
      analytics:[['Knowledge','Threat/product assessment and certification'],['Discovery','Persona coverage, pain depth, business-impact articulation'],['Technical readiness','Demo/PoC readiness score and scenario performance'],['Competitive','Objection handling and win/loss themes'],['Pipeline','Stage conversion, technical validation duration, cycle time'],['Business impact','Competitive win rate and revenue movement']],
      evidence:[['Curriculum','Threat-Centric Enablement','Complex security concepts translated into role-specific commercial and technical learning.',null],['Technical track','SE + Security Engineer Readiness','Advanced paths supported demo, architecture, and PoC execution.',null],['Measurement','Cyber GTM Readiness Scorecard','Technical proficiency, discovery quality, pipeline velocity, and competitive performance formed one proof model.',null]]
    },
    {
      id:'cofense-rebrand',company:'Cofense / PhishMe',title:'Rebrand & GTM Realignment — PhishMe to Cofense',role:'Director, Global Sales Enablement',timeline:'Global rebrand',type:'Change management + field activation',metrics:['Zero pipeline disruption','+4% win rate','−21 days cycle'],
      objective:'Translate a major corporate rebrand into field readiness so sellers, technical teams, managers, and partners could use the new positioning without disrupting active enterprise pipeline.',
      lede:'Converted a corporate rebrand from a marketing launch into a coordinated field-readiness and revenue-execution program.',
      why:'The market still associated PhishMe primarily with awareness training while the portfolio had expanded into phishing defense, threat intelligence, and automated incident response. Legacy language, product hierarchy, and value propositions could create buyer confusion and disrupt active deals.',
      how:'Built a mandatory global rebrand curriculum, mapped old-to-new product architecture, rebuilt playbooks, objections, competitive messaging, and value pillars, aligned Solution Engineer demos and technical narratives, certified field readiness, and supported the pipeline transition with manager reinforcement.',
      process:['Lock corporate narrative','Map old → new product architecture','Inventory affected field assets','Rebuild messaging + value pillars','Update playbooks + objections','Align competitive content','Brief + practice with SEs','Certify field readiness','Cut over active pipeline','Inspect adoption + buyer confusion'],
      pm:['Treated the rebrand as a change-management program across Sales, Marketing, Product, technical teams, managers, and partners.','Used a cutover inventory so old terminology and product naming were systematically removed from high-use field assets.','Sequenced seller and technical readiness before expecting the new narrative to appear consistently in live opportunities.','Monitored active pipeline and field feedback immediately after cutover so confusion could be corrected before it became revenue disruption.'],
      programs:['Rebrand enablement masterplan','Mandatory global curriculum','Old-to-new product mapping','Sales playbook overhaul','Objection framework','Competitive battlecards','Technical SE briefings','Field certification + reinforcement'],
      tools:['Global learning paths','Sales playbooks','Competitive battlecards','Technical workshops','Certification workflows','Manager reinforcement','Field communications'],
      outcomes:[['Zero','Enterprise pipeline disruption during transition'],['+8.75%','Bottom-line revenue growth during strategic growth phase'],['+4%','Competitive win-rate lift'],['−21 days','Average sales-cycle reduction tied to the realigned narrative']],
      note:'Corporate Strategy → Narrative → Product Architecture → Field Assets → Practice → Certification → Cutover → Pipeline Execution.',
      timeToImpact:'8-week readiness build before cutover · 30-day stabilization · quarterly adoption and revenue review',
      phases:[['01','Narrative lock','Week 1','Align company story, product hierarchy, proof points, and the specific behavior change required in the field.'],['02','Impact inventory','Week 2','Identify every high-use deck, playbook, battlecard, demo, training asset, and pipeline touchpoint requiring change.'],['03','Rebuild','Weeks 3–4','Update messaging, product architecture, discovery, objections, competition, and seller assets.'],['04','Technical alignment','Week 5','Rehearse SE demos, architecture language, automation story, and proof points.'],['05','Practice + certify','Weeks 6–7','Run mandatory global learning, manager reinforcement, practice, and readiness certification.'],['06','Cutover','Week 8','Launch the new narrative and product language across active pipeline and field channels.'],['07','Stabilize','First 30 days','Monitor buyer confusion, legacy-language usage, asset adoption, and deal risk; correct quickly.'],['08','Business review','Quarterly','Evaluate win rate, cycle time, pipeline continuity, and persistent adoption gaps.']],
      architecture:[['Corporate strategy','PhishMe → Cofense'],['Market story','Awareness training → threat intelligence + response'],['Field enablement','Messaging · objections · playbooks · competitive story'],['Technical layer','SE briefings + demo readiness'],['Readiness','Mandatory curriculum · practice · certification'],['Business output','Zero disruption + stronger velocity']],
      analytics:[['Readiness','Completion, certification, practice score, manager confirmation'],['Asset migration','New vs. legacy asset usage and stale-content retirement'],['Message adoption','Observed use of new terminology and value pillars'],['Pipeline continuity','At-risk opportunities, slippage, buyer confusion, cutover issues'],['Competitive performance','Win/loss reasons and competitive win rate'],['Business impact','Cycle time and revenue movement after stabilization']],
      evidence:[['Change plan','Rebrand Enablement Masterplan','Corporate strategy translated into a sequenced field-readiness and pipeline-protection plan.',null],['Technical artifact','SE Alignment System','Technical workshops ensured the new automation story held up in demonstrations and PoCs.',null],['Measurement','Cutover Readiness + Pipeline Dashboard','Readiness, asset migration, message adoption, and active-deal risk were inspected together.',null]]
    }
  ];

  function chips(items){return '<div class="tool-cloud">'+items.map(function(item){return '<span>'+item+'</span>'}).join('')+'</div>'}
  function listItems(items){return '<ul>'+items.map(function(item){return '<li>'+item+'</li>'}).join('')+'</ul>'}
  function processFlow(items){return '<div class="process-flow">'+items.map(function(item,i){return '<span class="process-step"><b>'+String(i+1).padStart(2,'0')+'</b>'+item+'</span>'}).join('')+'</div>'}
  function outcomeGrid(items){return '<div class="outcome-grid">'+items.map(function(item){return '<div class="outcome"><strong>'+item[0]+'</strong><span>'+item[1]+'</span></div>'}).join('')+'</div>'}
  function analyticsGrid(items){return '<div class="analytics-grid">'+items.map(function(item){return '<div class="analytics-item"><strong>'+item[0]+'</strong><span>'+item[1]+'</span></div>'}).join('')+'</div>'}
  function timelineViz(p){return '<div class="visual-card timeline-card"><div class="visual-card-head"><span>Execution roadmap</span><small>'+p.timeToImpact+'</small></div><div class="timeline-summary"><strong>Time to measurable impact</strong><span>'+p.timeToImpact+'</span></div><div class="project-timeline">'+p.phases.map(function(item){return '<div class="timeline-phase"><div class="timeline-marker"><span>'+item[0]+'</span></div><div class="timeline-copy"><small>'+item[2]+'</small><strong>'+item[1]+'</strong><p>'+item[3]+'</p></div></div>'}).join('')+'</div><p class="timeline-disclosure">Delivery windows are scope-based operating estimates reconstructed from the program design; reported outcome metrics are the results shown elsewhere in this case study.</p></div>'}
  function architectureViz(p){return '<div class="visual-card architecture-card"><div class="visual-card-head"><span>Systems architecture</span><small>How the work connected</small></div><div class="architecture-flow">'+p.architecture.map(function(item,i){return '<div class="architecture-node"><small>'+String(i+1).padStart(2,'0')+'</small><strong>'+item[0]+'</strong><span>'+item[1]+'</span></div>'}).join('')+'</div></div>'}
  function evidenceViz(p){if(!p.evidence||!p.evidence.length)return '';return '<div class="visual-card evidence-card-wrap"><div class="visual-card-head"><span>Proof + artifacts</span><small>Representative evidence without exposing confidential material</small></div><div class="evidence-grid">'+p.evidence.map(function(item){var body='<span class="evidence-type">'+item[0]+'</span><strong>'+item[1]+'</strong><p>'+item[2]+'</p><span class="evidence-cta">'+(item[3]?'View artifact ↗':'Evidence summary')+'</span>';return item[3]?'<a class="evidence-card" href="'+item[3]+'">'+body+'</a>':'<div class="evidence-card evidence-card-static">'+body+'</div>'}).join('')+'</div></div>'}
  function visualProof(p){return '<section class="project-proof" aria-label="Visual proof for '+p.title+'"><div class="proof-intro"><span>Operating model + proof</span><p>Sequence, system design, measurement, and representative evidence.</p></div><div class="proof-grid">'+timelineViz(p)+architectureViz(p)+'</div>'+evidenceViz(p)+'</section>'}

  list.classList.add('project-list');
  list.innerHTML=projects.map(function(p,index){
    var number=String(index+1).padStart(2,'0');
    return '<article class="project-case" id="'+p.id+'">'+
      '<button class="project-toggle" type="button" data-project-toggle aria-expanded="false" aria-controls="'+p.id+'-detail">'+
        '<span class="project-index">'+number+'</span>'+
        '<span class="project-heading"><small>'+p.company+' · '+p.timeline+'</small><h3>'+p.title+'</h3></span>'+
        '<span class="project-metrics">'+p.metrics.map(function(metric){return '<span class="project-metric">'+metric+'</span>'}).join('')+'</span>'+
        '<span class="project-action"><span>View project</span><span class="project-action-icon" aria-hidden="true">+</span></span>'+
      '</button>'+
      '<div class="project-detail" id="'+p.id+'-detail" hidden><div class="project-detail-inner">'+
        '<p class="project-lede">'+p.lede+'</p>'+
        '<div class="project-meta"><span>'+p.role+'</span><span>'+p.timeline+'</span><span>'+p.type+'</span></div>'+
        '<section class="project-block project-objective"><h4>Objective</h4><p>'+p.objective+'</p></section>'+
        visualProof(p)+
        '<div class="project-grid">'+
          '<section class="project-block"><h4>The challenge</h4><p>'+p.why+'</p></section>'+
          '<section class="project-block"><h4>Execution</h4><p>'+p.how+'</p></section>'+
          '<section class="project-block"><h4>Process implemented</h4>'+processFlow(p.process)+'</section>'+
          '<section class="project-block"><h4>Project management + operating cadence</h4>'+listItems(p.pm)+'</section>'+
          '<section class="project-block"><h4>Programs + deliverables</h4>'+listItems(p.programs)+'</section>'+
          '<section class="project-block"><h4>Tools + systems</h4>'+chips(p.tools)+'</section>'+
        '</div>'+
        '<section class="project-block measurement-system"><h4>Measurement system</h4><p class="measurement-intro">A high-performing enablement program is inspected across adoption, proficiency, behavior, and business outcomes—not completion alone.</p>'+analyticsGrid(p.analytics)+'</section>'+
        '<section class="project-block measured-outcomes"><h4>Outcomes + KPIs</h4>'+outcomeGrid(p.outcomes)+'</section>'+
        '<div class="project-note"><strong>Operating logic:</strong> '+p.note+'</div>'+
      '</div></div>'+
    '</article>';
  }).join('');

  list.querySelectorAll('[data-project-toggle]').forEach(function(button){
    button.addEventListener('click',function(){
      var expanded=button.getAttribute('aria-expanded')==='true';
      var caseEl=button.closest('.project-case');
      var detail=document.getElementById(button.getAttribute('aria-controls'));
      button.setAttribute('aria-expanded',String(!expanded));
      if(detail)detail.hidden=expanded;
      if(caseEl)caseEl.classList.toggle('is-open',!expanded);
      var label=button.querySelector('.project-action > span:first-child');
      if(label)label.textContent=expanded?'View project':'Close project';
    });
  });

  var kpiRows=document.querySelectorAll('.kpi-row');
  kpiRows.forEach(function(row){
    var label=row.querySelector('.kpi-label');
    var value=row.querySelector('.kpi-value');
    if(label&&value&&/faster ramp/i.test(label.textContent))value.textContent='40–50%';
  });
}());
